version: '3.8'
services:
  backend:
    build: ./backend
    container_name: serverapp_c
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    container_name: clientapp_c
    ports:
      - '5173:5173'
    volumes:
      - ./frontend/src:/app/src
    env_file:
      - ./env/frontend.env
    stdin_open: true
    tty: true
    depends_on:
      - backend
  mongo:
    image: mongo:latest
    restart: always
    ports:
        - "27017:27017"
    env_file:
      - ./env/mongo.env
