version: "3.8"
services:
  mongodb:
    image: bitnami/mongodb:latest
    container_name: mongo_c
    volumes:
      - mongo-data:/data/db
    env_file:
      - ./env/mongo.env
    restart: unless-stopped
    networks:
      - sandboxnet
    ports:
      - "27017:27017"
  backend:
    build: ./backend
    depends_on:
      - mongodb
    container_name: backend_c
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - sandboxnet
    env_file:
      - ./env/backend.env
  frontend:
    build: ./frontend
    depends_on:
      - backend
    container_name: frontend_c
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
    networks:
      - sandboxnet
    env_file:
      - ./env/frontend.env
    stdin_open: true
    tty: true
volumes:
  mongo-data:
networks:
  sandboxnet:
    driver: "bridge"
